# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - my-django-app-69ad5c

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput
      
        

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_04D616AA4F674F5F9A47DB008A203BFB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A2DCC628A71F48C495AE0F0A217DE0ED }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_93C5D08F9D904B79B8874E5DF955CF62 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'my-django-app-69ad5c'
          slot-name: 'Production'

      - name: Wait for app to become available
        run: |
          echo "⏳ Waiting 30 seconds for deployment to settle..."
          sleep 30
          
      - name: ✅ Health check - make sure app is running
        run: |
          for i in {1..10}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://my-django-app-69ad5c.azurewebsites.net)
            echo "HTTP status: $STATUS"
            if [ "$STATUS" = "200" ]; then
              echo "🎉 App is live!"
              exit 0
            fi
            echo "🔁 Retrying..."
            sleep 5
          done
          echo "❌ App failed health check."
          exit 1